//go:build linux

package network

import (
	"testing"
)

const ipRouteOutput = `
default via 192.168.1.1 dev eth0 proto dhcp src 192.168.1.42 metric 100
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.42
`

const ipRouteNoDefault = `
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.42
`

const resolvConf = `
# Generated by NetworkManager
nameserver 8.8.8.8
nameserver 8.8.4.4
search localdomain
`

const resolvConfEmpty = `
# no nameserver entries
search localdomain
`

const iwLinkConnected = `
Connected to aa:bb:cc:dd:ee:ff (on wlan0)
	SSID: MyHomeNetwork
	freq: 5180
	RX: 123456 bytes (1000 packets)
	TX: 78901 bytes (500 packets)
	signal: -62 dBm
	rx bitrate: 390.0 MBit/s
	tx bitrate: 390.0 MBit/s
`

const iwLinkDisconnected = `
Not connected.
`

const iwLink24GHz = `
Connected to aa:bb:cc:dd:ee:ff (on wlan0)
	SSID: Office2G
	freq: 2437
	signal: -71 dBm
`

func TestParseDefaultGatewayFromIPRoute(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{"has default gateway", ipRouteOutput, "192.168.1.1"},
		{"no default gateway", ipRouteNoDefault, ""},
		{"empty output", "", ""},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := parseDefaultGatewayFromIPRoute(tc.input); got != tc.want {
				t.Errorf("parseDefaultGatewayFromIPRoute() = %q, want %q", got, tc.want)
			}
		})
	}
}

func TestParseDNSServersFromResolvConf(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  []string
	}{
		{"two servers", resolvConf, []string{"8.8.8.8", "8.8.4.4"}},
		{"no nameservers", resolvConfEmpty, nil},
		{"empty content", "", nil},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := parseDNSServersFromResolvConf(tc.input)
			if len(got) != len(tc.want) {
				t.Fatalf("parseDNSServersFromResolvConf() = %v, want %v", got, tc.want)
			}
			for i := range got {
				if got[i] != tc.want[i] {
					t.Errorf("[%d] = %q, want %q", i, got[i], tc.want[i])
				}
			}
		})
	}
}

func TestParseWiFiInfoFromIW(t *testing.T) {
	t.Run("connected 5GHz", func(t *testing.T) {
		info := parseWiFiInfoFromIW(iwLinkConnected)
		if info == nil {
			t.Fatal("expected non-nil WiFiInfo")
			return // Early return to satisfy staticcheck
		}
		if info.SSID != "MyHomeNetwork" {
			t.Errorf("SSID = %q, want %q", info.SSID, "MyHomeNetwork")
		}
		if info.SignalStrength != -62 {
			t.Errorf("SignalStrength = %d, want -62", info.SignalStrength)
		}
		if info.FrequencyBand != "5GHz" {
			t.Errorf("FrequencyBand = %q, want 5GHz", info.FrequencyBand)
		}
	})
	t.Run("connected 2.4GHz", func(t *testing.T) {
		info := parseWiFiInfoFromIW(iwLink24GHz)
		if info == nil {
			t.Fatal("expected non-nil WiFiInfo")
			return // Early return to satisfy staticcheck
		}
		if info.FrequencyBand != "2.4GHz" {
			t.Errorf("FrequencyBand = %q, want 2.4GHz", info.FrequencyBand)
		}
	})
	t.Run("not connected returns nil", func(t *testing.T) {
		if got := parseWiFiInfoFromIW(iwLinkDisconnected); got != nil {
			t.Errorf("expected nil for disconnected, got %+v", got)
		}
	})
	t.Run("empty output returns nil", func(t *testing.T) {
		if got := parseWiFiInfoFromIW(""); got != nil {
			t.Errorf("expected nil for empty output, got %+v", got)
		}
	})
}

func TestFreqMHzToBand(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"2412", "2.4GHz"},
		{"2437", "2.4GHz"},
		{"2484", "2.4GHz"},
		{"5180", "5GHz"},
		{"5500", "5GHz"},
		{"5985", "5GHz"},
		{"6000", "6GHz"},
		{"6500", "6GHz"},
		{"1000", ""},
		{"abc", ""},
		{"", ""},
	}
	for _, tc := range tests {
		t.Run(tc.input, func(t *testing.T) {
			if got := freqMHzToBand(tc.input); got != tc.want {
				t.Errorf("freqMHzToBand(%q) = %q, want %q", tc.input, got, tc.want)
			}
		})
	}
}

func TestGetAdapterType(t *testing.T) {
	tests := []struct {
		name string
		want string
	}{
		{"wlan0", "WiFi"},
		{"wlp3s0", "WiFi"},
		{"wl0", "WiFi"},
		{"eth0", "Ethernet"},
		{"enp3s0", "Ethernet"},
		{"ens33", "Ethernet"},
		{"eno1", "Ethernet"},
		{"em1", "Ethernet"},
		{"lo", "Loopback"},
		{"tun0", "VPN"},
		{"tap0", "VPN"},
		{"vpn0", "VPN"},
		{"veth0", "Virtual"},
		{"docker0", "Virtual"},
		{"br-abc123", "Virtual"},
		{"virbr0", "Virtual"},
		{"ppp0", "Other"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := getAdapterType(tc.name); got != tc.want {
				t.Errorf("getAdapterType(%q) = %q, want %q", tc.name, got, tc.want)
			}
		})
	}
}

func TestGet_Linux_Integration(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping live network adapter collection in -short mode")
	}
	adapters := Get()
	for i, a := range adapters {
		t.Logf("adapter[%d]: name=%s type=%s status=%s connected=%v gw=%s dns=%v",
			i, a.InterfaceName, a.AdapterType, a.Status, a.IsConnected, a.DefaultGateway, a.DNSServers)
		if a.AdapterType == "" {
			t.Errorf("adapter[%d] %s: AdapterType is empty", i, a.InterfaceName)
		}
	}
}
